name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ok-nick/setup-aftman@v0.4.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Lint, format et typecheck
        run: bash tools/check.sh

      - name: Build Rojo
        run: rojo build default.project.json -o CSGO.rbxlx
